.\" Manpage for my_linter.
.\" Contact Alexandre JUAN to correct errors or typos.
.TH man 1 "13 September 2020" "1.6" "my_linter man page"
.SH NAME
my_linter \- check and correct ng lint errors
.SH SYNOPSIS
my_linter [-h|--help]
.SH DESCRIPTION
my_linter is an automatic corrector of ng lint's errors in any angular project.Automatic updates are available.
.SH OPTIONS
The my_linter does not take any options.
.SH SEE ALSO
Noting.
.SH BUGS
No known bugs.
.SH AUTHOR
Mitix-EPI (Alexandre JUAN) (https://github.com/Mitix-EPI)