#!/bin/bash

if [[ $EUID -ne 0 ]]; then
    echo "You must run this with superuser priviliges.  Try \"sudo ./install\"" 2>&1
    exit 1
else
    echo "Installing My Linter..."
fi

npm install

if [[ "$OSTYPE" == "linux-gnu" ]]; then
    sudo cp -rT node_modules /usr/local/bin/node_modules
    sudo cp -T my_linter /usr/local/bin/my_linter
fi
sudo chmod +x /usr/local/bin/my_linter

echo "Install dependencies"

echo "my_linter installed correctly"
