#!/bin/bash

if [[ $EUID -ne 0 ]]; then
    echo "You must run this with superuser priviliges.  Try \"sudo ./install\"" 2>&1
    exit 1
else
    echo "Installing My Linter..."
fi

if [[ "$OSTYPE" == "linux-gnu" ]]; then
    sudo cp my_linter /usr/local/bin/my_linter
fi
sudo chmod +x /usr/local/bin/my_linter

echo "Install dependencies"

npm install --save js-base64
npm install --save node-fetch
npm install --save child_process
npm install --save fs

echo "my_linter installed correctly"
